### PR TITLE
FusionPBX is under MPL License

### PR DESCRIPTION
**Pull request by markjcrane**
FusionPBX is not GPL it is license under MPL. No GPL code is allowed in the FusionPBX code base.

### CODE REVIEW

**Comment by EasyBB1** [comment]
FusionPBX is still MPL, I haven't changed it. I have also not changed its code base. The GPL selection is applicable to the image only as the image is basically Ubuntu and heaps of other GPL softwares.
I am not quite sure what all these license stuff means so please let me know if there is something specific that could violate FusionPBX MPL here and I am happy to change it.

**Comment by markjcrane** [comment]
If you state license for GPL then make sure its clear what you are stating is GPL which you have just done. "The GPL selection is applicable to the image only as the image is basically Ubuntu and heaps of other GPL softwares." My concern is the way its was done gives people the assumption that FusionPBX is GPL which is not true.

**Comment by EasyBB1** [comment]
I spoke with DigiDaz on IRC last night and then decided to remove the license file altogether. It is funny how things can turn out. When you create a release on github, you need to pick a license, so I chose the operating system's license.
I also came to know about your comments on IRC, like "unauthorized fork". An operating system image with fusion installed is considered to be a fork? This github repo doesn't host any fusionpbx source code.
Hoping to chat with you on IRC soon!

**Comment by markjcrane** [comment]
I saw the conversation last night on IRC. "unauthorized fork" was probably not the exact correct words to use. What I should have said instead is that you are unauthorized to the change or declare FusionPBX under a different license. Your license statement did not mention what was to be covered under that license. "cubox-fusionpbx" has fusionpbx in the name so it could be implied that you are stating the license of FusionPBX is GPL.

"This github repo doesn't host any fusionpbx source code."
FusionPBX source code is in your image that in your github repo.

 If you want to state a different license then please define what that license is supposed to cover.

**Pull request closed without merging**
